package com.miaoshaproject.dataobject;

public class UserDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.geender
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private Integer geender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.telphone
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.register_mode
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private String registerMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.third_party_id
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private String thirdPartyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.new_tablecol
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    private String newTablecol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.geender
     *
     * @return the value of user_info.geender
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public Integer getGeender() {
        return geender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.geender
     *
     * @param geender the value for user_info.geender
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setGeender(Integer geender) {
        this.geender = geender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.telphone
     *
     * @return the value of user_info.telphone
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.telphone
     *
     * @param telphone the value for user_info.telphone
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.register_mode
     *
     * @return the value of user_info.register_mode
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.register_mode
     *
     * @param registerMode the value for user_info.register_mode
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.third_party_id
     *
     * @return the value of user_info.third_party_id
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.third_party_id
     *
     * @param thirdPartyId the value for user_info.third_party_id
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.new_tablecol
     *
     * @return the value of user_info.new_tablecol
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public String getNewTablecol() {
        return newTablecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.new_tablecol
     *
     * @param newTablecol the value for user_info.new_tablecol
     *
     * @mbggenerated Sun Aug 25 23:18:19 CST 2019
     */
    public void setNewTablecol(String newTablecol) {
        this.newTablecol = newTablecol == null ? null : newTablecol.trim();
    }
}